nginx:
  image: "nginx:1.12"
  ports: 
    - 443:443
  links: 
    - registry:registry
  volumes: 
    - /Users/francoisdagostini/Projects/bcg/kubernetes/k8s-training/localdocker/nginx/:/etc/nginx/conf.d
registry:
  image: registry:2
  ports: 
    - 127.0.0.1:5000:5000
  environment: 
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
  volumes:
    - /Users/francoisdagostini/Projects/bcg/kubernetes/k8s-training/localdocker/data:/data