apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-09-15T15:16:32Z"
  generation: 2
  labels:
    app: try1
  name: try1
  namespace: default
  resourceVersion: "275571"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/try1
  uid: ccc5b818-d7cb-11e9-89a5-42010aa400c6
spec:
  progressDeadlineSeconds: 600
  replicas: 6
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: try1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: try1
    spec:
      containers:
      - image: gcr.io/test-project-k8s-252917/simpleapp:latest
        volumeMounts:
          - mountPath: /etc/cars
            name: car-vol
          - mountPath: /opt
            name: nfs-vol
        env:
          - name: ilike
            valueFrom:
                configMapKeyRef:
                  key: favorite
                  name: colors
        envFrom:
          - configMapRef:
              name: colors
        imagePullPolicy: Always
        name: simpleapp
        readinessProbe:
            periodSeconds: 5
            exec:
              command:
                - ls
                - /etc/cars
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - name: goproxy
        image: k8s.gcr.io/goproxy:0.1
        ports:
          - containerPort: 8080
        readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
        livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: car-vol
          configMap:
              defaultMode: 420
              name: fast-car
        - name: nfs-vol
          persistentVolumeClaim:
              claimName: pvc-one
status:
  availableReplicas: 6
  conditions:
  - lastTransitionTime: "2019-09-15T15:16:32Z"
    lastUpdateTime: "2019-09-15T15:17:04Z"
    message: ReplicaSet "try1-5664c44c5d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2019-09-15T15:29:24Z"
    lastUpdateTime: "2019-09-15T15:29:24Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 6
  replicas: 6
  updatedReplicas: 6
